# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fb9b9738ba606da6410efcc0bf384ed860e30e4ee981a98d4f43fb517d28f0dbbd9f412ada65b8160b20773b4fe12cfb664cf8630e1d49015260b0454b50068

test:
  secret_key_base: e355494a780ec1b9d3bb849259104488e582bfb04081b2a253ec39bb9b36043ef0706149bcc354bb780712294bfb3458caf95bc100a8e3f1f0c4db9f71a8c8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
